apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: web-app-dev
spec:
  containers:
    - name: myapp
      image: localhost:5000/simple_app

      imagePullPolicy: Always
      ports:
        - name: myapp
          containerPort: 8080
          protocol: TCP