apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: web-app-dev
spec:
  containers:
    - name: myapp
      image: crccheck/hello-world

      imagePullPolicy: Always
      ports:
        - name: myapp
          containerPort: 8000
          protocol: TCP