apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp-deplyment
  namespace: demo-cluster-ip
  labels:
    app: goapp-cluster-ip
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp-cluster-ip
  template:
    metadata:
      labels:
        app: goapp-cluster-ip
    spec:
      containers:
      - name: web-cluster-ip
        image: crccheck/hello-world
        ports:
        - containerPort: 8000